[[buildpacks]]
  uri = "urn:cnb:registry:paketo-buildpacks/python@2.15.0"
  version = "2.15.0"

[[buildpacks]]
  uri = "urn:cnb:registry:paketo-buildpacks/pip-install@0.6.1"
  version = "0.6.1"

[[buildpacks]]
  uri = "urn:cnb:registry:paketo-buildpacks/procfile@5.6.9"
  version = "5.6.9"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.15.0"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.6.1"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.9"

[build]
image = "diablo02000/buildpack-base-build:python3-ffmpeg"

[run]
[[run.images]]
image = "diablo02000/buildpack-base-run:python3-ffmpeg"

